# Generated by Django 5.2 on 2025-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="test3app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticketID", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("name2", models.CharField(max_length=255)),
            ],
        ),
    ]
