# Generated by Django 5.2 on 2025-05-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_test_imagepath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="description",
        ),
        migrations.RemoveField(
            model_name="test",
            name="imagePath",
        ),
        migrations.RemoveField(
            model_name="test",
            name="name",
        ),
    ]
