# Generated by Django 5.2 on 2025-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test3app",
            name="name3",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
